### ISSUE TITLE
unmi V2 pro printing 'r' before actual receipt text

### ISSUE THREAD

**Issue by codevjs** [paystory-de/thermal-printer-cordova-plugin#20]
I am using a Sunmi V2 Pro device which has an integrated printer.

I am using your ESC POS library to print receipts and having the following issue.
Only on these sunmi devices, there is a preceding 'r' printed before the 1st character.

**Comment by patrickbussmann** [comment]
Oh I think your device is similar to one of mine: Its not a real ESC POS printer. Its a "copy".
Please try this plugin instead: https://github.com/paystory-de/cordova-plugin-iposprinter

Or maybe your printer manufacturer have a custom API implementation.

Its a bit complicated sometimes.
Seems that only this "integrated" printers are affected by this.
If we're using real POS Printers we never had issues with that.

But the integrated also prints two new lines instead of one.
Dont know why the translation is not working so good.

Let me know if its work with IPosPrinterService plugin above.
